/**
 * The link to ONE section's full photo archive: the section's own sub-folder
 * inside the job's main photo folder.
 *
 * The app saves every photo under `{root}/{job number}/{section key}/...`
 * (acespect-mobile's syncManager uploads with the section key as the first
 * folder level; backend/src/lib/storage.ts names the job folder). The job
 * folder's link is generated by the backend (`Inspection.photoArchiveUrl`), so
 * a section's folder is that link plus the section key as one more path
 * segment. The key is cleaned exactly the way storage.ts cleans it
 * (anything other than letters, digits, "_" and "-" becomes "_"), so the link
 * always matches the real folder name.
 */
export function sectionPhotoArchiveUrl(jobFolderUrl: string | null | undefined, sectionKey: string | null | undefined): string | null {
  if (!jobFolderUrl || !sectionKey) return null;
  const segments = sectionKey
    .split(":")
    .map((part) => part.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 100))
    .filter(Boolean);
  if (segments.length === 0) return null;
  return `${jobFolderUrl.replace(/\/$/, "")}/${segments.join("/")}`;
}
